---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    groups:
      minor-and-patch-py:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
      - "dev"
      - "python"
    cooldown:
      default-days: 7

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      minor-and-patch-go:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
      - "go"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "/"
    groups:
      minor-and-patch-npm:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
      - "dev"
      - "javascript"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
      - "dev"
      - "github_actions"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"
    ignore:
      - dependency-name: "esacteksab/go"
        update-types: ["version-update:semver-minor"]
    labels:
      - "dependencies"
      - "dev"
      - "docker"
    cooldown:
      default-days: 7
