name: Go - Audit

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit-reusable:
    uses: esacteksab/.github/.github/workflows/go-ci.yml@4da97b8ebf8da80991b54006d530f0f1f4ca4404  # v0.80.35
