name: goreleaser

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser-reusable:
    uses: esacteksab/.github/.github/workflows/go-release.yml@1dde24dd0abe3f80e8bf9ffe22cc04b82f485079  # v0.82.5
