name: goreleaser

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser-reusable:
    uses: esacteksab/.github/.github/workflows/go-release.yml@7c06e185ed5558f9f37b1eef3d5e954921fc8f0f  # v0.87.7
