name: goreleaser

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser-reusable:
    uses: esacteksab/.github/.github/workflows/go-release.yml@2ee248cf7575840757c1d43548ad6ef4d1d62ada  # v0.80.6
