name: Go - Test

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go-test:
    uses: esacteksab/.github/.github/workflows/go-test.yml@2ee248cf7575840757c1d43548ad6ef4d1d62ada  # v0.80.6
