name: Go - Test

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go-test:
    uses: esacteksab/.github/.github/workflows/go-test.yml@5b6c977136c586995f61956f86ae361deb634c92  # v0.81.0
