name: Go - Test In Docker

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go-test-docker:
    uses: esacteksab/.github/.github/workflows/go-test-in-docker.yml@7d7d9f2d6f8782e0db28cb2c7b9dc7212cf18367  # v0.80.21
