name: golangci-lint

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  pull_request:
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci-reusable:
    uses: esacteksab/.github/.github/workflows/golangci-lint.yml@e2eea3a5d6e846dfc19ebbd3096a398b5de4cb67  # v0.80.26
