name: Labeler

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    uses: esacteksab/.github/.github/workflows/labeler.yml@4da97b8ebf8da80991b54006d530f0f1f4ca4404  # v0.80.35
