name: Pre-Commit

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SKIP: ${{ vars.SKIP }}

permissions:
  contents: read

jobs:
  precommit-reusable:
    uses: esacteksab/.github/.github/workflows/pre-commit.yml@7c06e185ed5558f9f37b1eef3d5e954921fc8f0f  # v0.87.7
