name: Spell Check

permissions:
  contents: read

on: [pull_request]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  typos-reusable:
    uses: esacteksab/.github/.github/workflows/spelling.yml@4da97b8ebf8da80991b54006d530f0f1f4ca4404  # v0.80.35
