name: Spell Check

permissions:
  contents: read

on: [pull_request]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  typos-reusable:
    uses: esacteksab/.github/.github/workflows/spelling.yml@8420fa6b741c470a27f76beb29655ebace3ab33d  # v0.85.6
