name: Spell Check

permissions:
  contents: read

on: [pull_request]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  typos-reusable:
    uses: esacteksab/.github/.github/workflows/spelling.yml@894dd32ed82c521205509499390c9ef22955b2dc  # v0.87.0
